"""
Flat Bar Stiffener (扁铁加强筋) - Ship Stiffener Model
Generated by MarineAgent

Parameters:
  width = 150 mm (高度/宽度)
  thickness = 12 mm (板厚)
  length = 3000 mm (长度)
"""
import cadquery as cq

# === 参数 ===
width = 150       # 高度/宽度 (mm)
thickness = 12    # 板厚 (mm)
length = 3000     # 长度 (mm)

# === 构建几何 ===
# 扁铁截面为矩形，在 XY 平面上绘制，沿 Z 轴挤出
part = (
    cq.Workplane("XY")
    .rect(width, thickness)
    .extrude(length)
)

# === 导出 STEP ===
output_file = "flat_bar.step"
cq.exporters.export(part, output_file)
print(f"Exported: {output_file}")
