"""
L-Bar / Angle Steel Stiffener (L型材/角钢加强筋) - Ship Stiffener Model
Generated by MarineAgent

Parameters:
  leg_a = 100 mm    (水平肢长度)
  leg_b = 150 mm    (垂直肢长度)
  thickness = 12 mm (板厚)
  length = 3000 mm  (长度)
"""
import cadquery as cq

# === 参数 ===
leg_a = 100       # 水平肢长度 (mm)
leg_b = 150       # 垂直肢长度 (mm)
thickness = 12    # 板厚 (mm)
length = 3000     # 长度 (mm)

# === 构建几何 ===
# L型截面以水平肢左下角为原点
# X轴：水平肢方向，Y轴：垂直肢方向，Z轴：挤出方向（长度）
#
#    +--+
#    |  |
#    |  |        leg_b - thickness
#    |  |
#    |  +--------+
#    |             |  thickness
#    +-------------+
#        leg_a

part = (
    cq.Workplane("XY")
    .moveTo(0, 0)
    .lineTo(leg_a, 0)
    .lineTo(leg_a, thickness)
    .lineTo(thickness, thickness)
    .lineTo(thickness, leg_b)
    .lineTo(0, leg_b)
    .close()
    .extrude(length)
)

# === 导出 STEP ===
output_file = "l_bar.step"
cq.exporters.export(part, output_file)
print(f"Exported: {output_file}")
