"""
T-Bar Stiffener (T型材加强筋) - Ship Stiffener Model
Generated by MarineAgent

Parameters:
  flange_w = 150 mm (面板宽度)
  flange_t = 12 mm  (面板厚度)
  web_h = 150 mm    (腹板高度)
  web_t = 10 mm     (腹板厚度)
  length = 3000 mm  (长度)
"""
import cadquery as cq

# === 参数 ===
flange_w = 150    # 面板宽度 (mm)
flange_t = 12     # 面板厚度 (mm)
web_h = 150       # 腹板高度 (mm)
web_t = 10        # 腹板厚度 (mm)
length = 3000     # 长度 (mm)

# === 构建几何 ===
# T型截面以面板底部中心为原点
# X轴：面板宽度方向，Y轴：高度方向，Z轴：挤出方向（长度）
#
#          web_t
#         +--+
#         |  |      web_h
#         |  |
#    +----+--+----+
#    |             |  flange_t
#    +-------------+
#        flange_w

half_fw = flange_w / 2
half_wt = web_t / 2

part = (
    cq.Workplane("XY")
    .moveTo(-half_fw, 0)
    .lineTo(half_fw, 0)
    .lineTo(half_fw, flange_t)
    .lineTo(half_wt, flange_t)
    .lineTo(half_wt, flange_t + web_h)
    .lineTo(-half_wt, flange_t + web_h)
    .lineTo(-half_wt, flange_t)
    .lineTo(-half_fw, flange_t)
    .close()
    .extrude(length)
)

# === 导出 STEP ===
output_file = "t_bar.step"
cq.exporters.export(part, output_file)
print(f"Exported: {output_file}")
